import { CANDIDATE_STAGES, ROLES } from "../osData";
import { Avatar, PageHeading, Panel, Tag } from "../ui";
import { ApplicantOverview } from "./Dashboard";

export function HrPage({ store, viewer, moveCandidate }) {
  if (viewer.role === "applicant") return <ApplicantOverview store={store} viewer={viewer} setActive={() => {}}/>;
  const canEdit = ["admin", "hr"].includes(viewer.role);
  return <div className="page"><PageHeading eyebrow="HR recruitment channel" title="Candidate review and controlled invitations" text="People apply publicly, HR reviews them through the recruitment pipeline, and work access is only invited when a candidate is hired." action={<Tag tone="success">HR protected</Tag>}/><div className="hr-flow">{CANDIDATE_STAGES.map((stage) => <section key={stage}><header><span>{stage}</span><b>{store.candidates.filter((candidate) => candidate.stage === stage).length}</b></header>{store.candidates.filter((candidate) => candidate.stage === stage).map((candidate) => <article key={candidate.id}><div className="candidate-score">{candidate.score || "—"}</div><strong>{candidate.name}</strong><small>{candidate.role} · {candidate.department}</small><p>{candidate.notes}</p>{canEdit && !["Hired", "Rejected"].includes(candidate.stage) && <button onClick={() => moveCandidate(candidate)}>{candidate.stage === "Offer" ? "Hire and invite" : `Move to ${CANDIDATE_STAGES[Math.min(CANDIDATE_STAGES.indexOf(candidate.stage) + 1, CANDIDATE_STAGES.length - 1)]} →`}</button>}</article>)}</section>)}</div><div className="split-grid"><Panel eyebrow="Active work accounts" title="People directory"><div className="employee-list">{store.users.filter((user) => !["client", "applicant"].includes(user.role)).map((user) => <div key={user.id}><Avatar user={user}/><div><strong>{user.name}</strong><small>{ROLES[user.role].label} · {user.department}</small></div><Tag tone={user.status === "Active" ? "success" : "warning"}>{user.status}</Tag></div>)}</div></Panel><Panel eyebrow="Controlled process" title="HR access policy"><div className="rule-list"><span>1. Applicant applies through the public HR channel</span><span>2. HR moves candidates through review stages</span><span>3. Offer is approved and candidate is hired</span><span>4. Elite OS creates an invitation</span><span>5. Department role determines the workspace</span></div></Panel></div></div>;
}
