import { useState } from "react";
import { DEPARTMENTS, ROLES, SERVICE_CATALOG } from "../osData";
import { formatMoney } from "../osLogic";
import { Avatar, Button } from "../ui";

function Brand() {
  return <div className="landing-brand"><div className="brand-mark">E</div><div><span>Elite Era Development L.L.C</span><strong>Elite OS</strong></div></div>;
}

function AuthCard({ title, text, children, onBack }) {
  return <div className="auth-shell"><button className="auth-back" onClick={onBack}>← Back to Elite OS</button><div className="auth-card"><Brand/><div className="auth-copy"><h1>{title}</h1><p>{text}</p></div>{children}<div className="auth-footer">Made by <strong>Hira Khyzer</strong> · #f4af00</div></div></div>;
}

export function Landing({ setMode }) {
  return <div className="landing">
    <header className="landing-nav"><Brand/><div className="landing-actions"><button onClick={() => setMode("apply")}>Careers</button><button onClick={() => setMode("login")}>Sign in</button><Button onClick={() => setMode("register")}>Client registration</Button></div></header>
    <main>
      <section className="landing-hero"><div className="hero-copy"><p className="eyebrow">Business operating system</p><h1>One intelligent workspace for every Elite Era relationship.</h1><p>From first client question to delivery, payment, renewal, and employee growth—Elite OS connects your full company workflow with the right access for every role.</p><div className="hero-buttons"><Button onClick={() => setMode("register")}>Request a service <span>→</span></Button><Button onClick={() => setMode("login")} variant="outline">Open Elite OS</Button></div><div className="hero-note"><span>◉</span> Client, employee, HR applicant, and founder experiences are separated by role.</div></div><div className="hero-visual"><div className="orb orb-one"/><div className="orb orb-two"/><div className="visual-top"><span>Elite OS intelligence</span><b>Live</b></div><div className="visual-price"><span>Pipeline value</span><strong>$64,700</strong><small>4 qualified opportunities</small><div className="sparkline"><i/><i/><i/><i/><i/><i/><i/></div></div><div className="visual-grid"><div><span>Projects</span><b>3</b><small>1 at risk</small></div><div><span>Support</span><b>3</b><small>Open tickets</small></div><div><span>HR</span><b>3</b><small>Active candidates</small></div><div><span>Automation</span><b>8</b><small>Business rules</small></div></div><div className="workflow-chip one">AI bot routes client request <b>→ Sales</b></div><div className="workflow-chip two">Quote accepted <b>→ Onboarding</b></div><div className="workflow-chip three">Candidate hired <b>→ Invite access</b></div></div></section>
      <section className="landing-strip"><p>Designed for a complete Elite Era workflow</p><div><span>Lead</span><b>→</b><span>Quote</span><b>→</b><span>Proposal</span><b>→</b><span>Onboarding</span><b>→</b><span>Delivery</span><b>→</b><span>Finance</span><b>→</b><span>Renewal</span></div></section>
      <section className="landing-section"><div className="section-heading"><p className="eyebrow">Built for every participant</p><h2>One system. Different secure experiences.</h2></div><div className="role-cards"><article><i>◆</i><h3>Founder & Admin</h3><p>Revenue, risk, approvals, users, departments, audit logs, and technical controls.</p></article><article><i>◫</i><h3>Employees</h3><p>Department-specific workspaces with only assigned clients, projects, tasks, and approvals.</p></article><article><i>◉</i><h3>Clients</h3><p>Service requests, proposals, onboarding, delivery updates, files, invoices, and support.</p></article><article><i>◎</i><h3>Applicants</h3><p>Proper HR channel for applications, screening, interviews, offers, and invitations.</p></article></div></section>
      <section className="landing-section service-showcase"><div className="section-heading"><p className="eyebrow">Smart service intake</p><h2>Each request is routed to the right department.</h2></div><div className="service-grid">{SERVICE_CATALOG.map((service) => <article key={service.id}><span>{service.department}</span><h3>{service.label}</h3><p>{service.description}</p><b>From {formatMoney(service.base)}</b></article>)}</div></section>
    </main>
    <footer className="landing-footer"><strong>Made by Hira Khyzer</strong><span>Elite Era Development L.L.C</span><b>#f4af00</b></footer>
  </div>;
}

export function Login({ store, onLogin, setMode }) {
  const accounts = store.users.filter((user) => user.status === "Active" || user.role === "client");
  return <AuthCard title="Sign in to Elite OS" text="Choose a demo account to explore exactly what each role can see." onBack={() => setMode("landing")}><div className="login-grid">{accounts.map((user) => <button className="login-option" key={user.id} onClick={() => onLogin(user.id)}><Avatar user={user}/><div><strong>{user.name}</strong><span>{ROLES[user.role].label}</span></div><i>→</i></button>)}</div><div className="auth-divider"><span>or start an account</span></div><div className="auth-actions"><Button variant="outline" onClick={() => setMode("register")}>Client registration</Button><Button variant="outline" onClick={() => setMode("apply")}>Apply through HR</Button></div></AuthCard>;
}

export function ClientRegistration({ onRegister, setMode }) {
  const [form, setForm] = useState({ name: "", email: "", company: "", service: "web", budget: "", message: "" });
  const change = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <AuthCard title="Start your Elite Era journey" text="Create a client account and tell us what your business needs. Your request will be routed to the right team." onBack={() => setMode("landing")}><form className="form" onSubmit={(event) => { event.preventDefault(); onRegister(form); }}><div className="form-grid"><label>Full name<input required value={form.name} onChange={(event) => change("name", event.target.value)} placeholder="Your name"/></label><label>Business email<input required type="email" value={form.email} onChange={(event) => change("email", event.target.value)} placeholder="you@company.com"/></label><label>Company name<input required value={form.company} onChange={(event) => change("company", event.target.value)} placeholder="Your company"/></label><label>Primary service<select value={form.service} onChange={(event) => change("service", event.target.value)}>{SERVICE_CATALOG.map((service) => <option value={service.id} key={service.id}>{service.label}</option>)}</select></label><label>Estimated budget<input type="number" value={form.budget} onChange={(event) => change("budget", event.target.value)} placeholder="e.g. 10000"/></label><label>Request details<textarea value={form.message} onChange={(event) => change("message", event.target.value)} placeholder="Tell us about your goals, timeline, or requirements." rows="3"/></label></div><Button className="wide">Create client account and request service →</Button></form><p className="form-note">Your account begins in pending verification. Sales receives the request and an Elite OS record is created automatically.</p></AuthCard>;
}

export function JobApplication({ onApply, setMode }) {
  const [form, setForm] = useState({ name: "", email: "", role: "Developer", department: "Technical", portfolio: "", note: "" });
  const change = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <AuthCard title="Apply through the HR channel" text="Employee access is granted only after HR screening, assessment, offer approval, and an official invitation." onBack={() => setMode("landing")}><form className="form" onSubmit={(event) => { event.preventDefault(); onApply(form); }}><div className="form-grid"><label>Full name<input required value={form.name} onChange={(event) => change("name", event.target.value)} placeholder="Your name"/></label><label>Email<input required type="email" value={form.email} onChange={(event) => change("email", event.target.value)} placeholder="you@email.com"/></label><label>Role you are applying for<select value={form.role} onChange={(event) => change("role", event.target.value)}><option>Developer</option><option>Sales Executive</option><option>Project Manager</option><option>Marketing Specialist</option><option>Finance Associate</option><option>Support Specialist</option></select></label><label>Preferred department<select value={form.department} onChange={(event) => change("department", event.target.value)}>{DEPARTMENTS.filter((department) => department.id !== "Executive").map((department) => <option key={department.id}>{department.id}</option>)}</select></label><label>Portfolio / LinkedIn<input value={form.portfolio} onChange={(event) => change("portfolio", event.target.value)} placeholder="https://..."/></label><label>Short introduction<textarea value={form.note} onChange={(event) => change("note", event.target.value)} placeholder="Experience, strengths, availability..." rows="3"/></label></div><Button className="wide">Submit HR application →</Button></form><p className="form-note">Applicants receive a separate profile and cannot access client, finance, project, or employee records.</p></AuthCard>;
}
